-- Corregir tipos de columnas id de INTEGER a BIGINT
ALTER TABLE vehiculos ALTER COLUMN id TYPE BIGINT;
ALTER TABLE espacios ALTER COLUMN id TYPE BIGINT;
ALTER TABLE tarifas ALTER COLUMN id TYPE BIGINT;
ALTER TABLE pagos ALTER COLUMN id TYPE BIGINT;
ALTER TABLE usuarios ALTER COLUMN id TYPE BIGINT;
