spring:
  application:
    name: ParkFlow360
  
  datasource:
    url: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.pmijcynowbvxvqrratst
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:clave-secreta-jwt-muy-segura-y-larga-para-parkflow360}
  expiration: 86400000
